name: navigwiz
description: Open-source Navigwiz browser with custom search and Apex Ai
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  webview_flutter: ^4.2.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  image: ^4.0.17
  url_launcher: ^6.1.12
  file_picker: ^8.0.0+1
  permission_handler: ^11.0.1
  flutter_colorpicker: ^1.0.3
  openai_api: ^0.3.7
  crypto: ^3.0.3
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  intl: ^0.20.2
  package_info_plus: ^8.0.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  image_picker: ^1.1.2
  camera: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
