name = "acronous-ai"
main = "src/index.js"
compatibility_date = "2025-04-01"

[vars]
ENVIRONMENT = "production"

[env.production]
vars = {
  SEARCH_ENABLED = "true",
  ENVIRONMENT = "production"
}

[env.development]
vars = {
  SEARCH_ENABLED = "false",
  ENVIRONMENT = "development"
}